// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk6s12AwOtLZaIEHz4uD_TKj2ephYveos',
    appId: '1:1033940901812:web:3f08bcf85607ede1df1ce1',
    messagingSenderId: '1033940901812',
    projectId: 'fir-bookmark-c7f57',
    authDomain: 'fir-bookmark-c7f57.firebaseapp.com',
    storageBucket: 'fir-bookmark-c7f57.appspot.com',
    measurementId: 'G-XV007DF0DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuL_1uknYkL5El5tgmct1Zh6njdfRbkpw',
    appId: '1:1033940901812:android:a08d354df9369ebcdf1ce1',
    messagingSenderId: '1033940901812',
    projectId: 'fir-bookmark-c7f57',
    storageBucket: 'fir-bookmark-c7f57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAO0qOSxpR4GtO5ZvoDYgkUiTUKjMIWz4',
    appId: '1:1033940901812:ios:5a54c78ea5f68ebddf1ce1',
    messagingSenderId: '1033940901812',
    projectId: 'fir-bookmark-c7f57',
    storageBucket: 'fir-bookmark-c7f57.appspot.com',
    iosBundleId: 'com.example.firebaseBookmark',
  );
}
